lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem' 
    pass_phrase: 'your_passphrase'                           
    token_ttl: 3600                                          

    api_platform:
        check_path: 'email'        
        username_path: 'username'  
        password_path: 'password'  
